### ISSUE TITLE
[1.14-fabric0.2.7-1.4] - Can no longer set key-bindings under controls

### ISSUE THREAD

**Issue by spradlin-dev** [gbl/Grid#7] opened 2019-10-20 22:30 UTC
Mod Version: 1.14-fabric0.2.7-1.4
Fabric API: v0.4.0+build.240-1.14
Client Commands: v0.2.1+1.14-pre5
Cloth Config: v0.2.1+build.14

Ever since I updated to the latest fabric/1.14.4 version, I have no option to set the key-bindings.  I like setting the spawn areas to F12, and used to have this set, but now it doesn't show up under controls.

**Comment by gbl** [comment] 2020-06-24 08:04
Closing this as the issue is quite old, and the 1.16 version definitely allows you to set the key bindings.

**Closed as completed by gbl** 2020-06-24 08:04 UTC
